import { useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, BookOpen, Headphones, ShieldCheck, Sparkles } from 'lucide-react';
import { articles } from '../data.js';
import { useLanguage } from '../i18n.jsx';
import { ArticleCard, ButtonLink, PageIntro, SectionHeading } from '../components/Common.jsx';

export function JournalPage() {
  const { t } = useLanguage();
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All notes');
  const categories = ['All notes', ...new Set(articles.map((article) => article.category))];
  const filtered = useMemo(() => articles.filter((article) => (category === 'All notes' || article.category === category) && `${article.title} ${article.titleVi} ${article.summary}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  return <main id="main" className="interior-page journal-page"><section className="interior-hero page-container journal-intro"><PageIntro eyebrow="NOTES FROM THE COURSE" title="Study the small" accent="details." body={t('journalIntro')} /><div className="journal-cover-art"><span className="journal-cover-small">LANGUAGE NOTES · 01</span><span className="journal-cover-char">ạ</span><span className="journal-cover-caption">WORDS IN<br />REAL CONTEXT</span><span className="journal-cover-spark">✳</span></div></section><section className="section section-paper journal-library-section"><div className="page-container"><div className="journal-toolbar"><div className="filter-pills" role="group" aria-label="Filter study notes">{categories.map((item) => <button key={item} type="button" className={category === item ? 'filter-pill active' : 'filter-pill'} onClick={() => setCategory(item)} aria-pressed={category === item}>{item === 'All notes' ? 'All notes' : item}</button>)}</div><label className="lesson-search"><BookOpen size={16} /><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search study notes…" aria-label="Search study notes" /></label></div>{filtered.length ? <div className="article-grid journal-article-grid">{filtered.map((article) => <ArticleCard key={article.slug} article={article} />)}</div> : <div className="empty-state"><BookOpen size={22} /><h3>{t('noResult')}</h3><p>Try another category or keyword.</p></div>}</div></section></main>;
}

export function ArticlePage() {
  const { slug } = useParams();
  const article = articles.find((item) => item.slug === slug);
  if (!article) return <NotFoundPage />;
  return <main id="main" className="article-detail-page"><div className="page-container article-detail-container"><Link className="back-link" to="/journal"><ArrowLeft size={16} />Back to study notes</Link><header className="article-detail-header"><p className="eyebrow"><span className="eyebrow-dot" />{article.category}</p><h1>{article.title}</h1><p className="article-detail-summary">{article.summary}</p><div className="article-detail-meta"><span>{article.read}</span><span>VIETSOUND · LANGUAGE NOTE</span></div></header><div className="article-detail-art"><span>{article.slug === 'a-polite-particle' ? 'ạ' : article.titleVi.charAt(0)}</span><i>✳</i></div><article className="article-body">{article.paragraphs.map((paragraph, index) => <p key={index}>{paragraph}</p>)}{article.slug === 'a-polite-particle' && <div className="article-examples"><h2>Try these examples</h2><p><strong>Vâng ạ.</strong><span>Yes, certainly.</span></p><p><strong>Con chào mẹ ạ.</strong><span>Hi, Mom. (respectful / warm)</span></p><p><strong>Con mới về nhà ạ.</strong><span>I just got home.</span></p></div>}<div className="article-source-note"><ShieldCheck size={17} /><span>Language note for learning. Regional usage and relationships matter; ask a speaker or tutor when a phrase is sensitive.</span></div></article><div className="article-bottom-nav"><Link className="back-link" to="/journal"><ArrowLeft size={16} />All study notes</Link><ButtonLink to="/course" kind="coral">Practise in the course</ButtonLink></div></div></main>;
}

export function AboutPage() {
  return <main id="main" className="interior-page about-page"><section className="interior-hero page-container"><PageIntro eyebrow="ABOUT THIS LEARNING SPACE" title="Learn meaning first." accent="Build confidence next." body="Vietsound is a Vietnamese learning project centred on clear sounds, comprehensible input and real communication. This version turns the original information page into a self-paced study space." /><div className="about-method-stamp"><span>TPR</span><i>✳</i><span>TPRS</span><strong>TIẾNG VIỆT</strong><small>LEARN · LISTEN · USE</small></div></section><section className="section section-paper"><div className="page-container"><SectionHeading eyebrow="THE TEACHING APPROACH" title="A practical mix of input, movement and structure." body="The original Vietsound material describes TPR, TPRS, the Natural Approach and focused grammar. Here is how those ideas connect to the course." /><div className="about-method-grid"><article><span>01</span><h3>Hear and understand</h3><p>Short language chunks come with context, examples and a chance to listen again.</p></article><article><span>02</span><h3>Respond with meaning</h3><p>TPR links simple language to a physical response; a learner can demonstrate understanding before speaking.</p></article><article><span>03</span><h3>Meet language in stories</h3><p>TPRS returns useful words in a story so they become easier to recognise and remember.</p></article><article><span>04</span><h3>Notice the pattern</h3><p>Grammar notes make a structure explicit after the learner has seen it doing a job in context.</p></article></div></div></section><section className="section about-course-section"><div className="page-container about-course-layout"><div><p className="eyebrow"><span className="eyebrow-dot" />A SELF-PACED COURSE</p><h2>No paywall.<br /><em>Start with lesson one.</em></h2><p>The A1 course is open in this build. Lessons, dictionary, stories and pronunciation tools are available without an account. Progress is kept locally in your browser.</p></div><ButtonLink to="/course" kind="coral">Open the course</ButtonLink></div></section></main>;
}

export function HelpPage() {
  const { t } = useLanguage();
  const questions = [['helpQ1', 'helpA1'], ['helpQ2', 'helpA2'], ['helpQ3', 'helpA3'], ['helpQ4', 'helpA4'], ['helpQ5', 'helpA5']];
  const [open, setOpen] = useState(0);
  return <main id="main" className="interior-page help-page"><section className="interior-hero page-container"><PageIntro eyebrow="STUDY SUPPORT" title={t('helpTitle')} accent="at your pace." body={t('helpBody')} /><div className="help-stamp"><Headphones size={28} /><span>LISTEN<br />AGAIN</span><i>✳</i></div></section><section className="section section-paper"><div className="page-container help-layout"><div><p className="eyebrow"><span className="eyebrow-dot" />COMMON QUESTIONS</p><h2>Get unstuck and keep learning.</h2><p className="help-audio-note"><Headphones size={17} />Audio depends on the Vietnamese voice available on your device. You can read every example even if speech synthesis is unavailable.</p><ButtonLink to="/course" kind="text">Return to the course</ButtonLink></div><div className="grammar-accordion">{questions.map(([q, a], index) => <article className={`grammar-topic ${open === index ? 'open' : ''}`} key={q}><button type="button" onClick={() => setOpen(open === index ? -1 : index)} aria-expanded={open === index}><span className="grammar-topic-no">0{index + 1}</span><strong>{t(q)}</strong><span className="faq-toggle">{open === index ? '−' : '+'}</span></button>{open === index && <p>{t(a)}</p>}</article>)}</div></div></section></main>;
}

export function PrivacyPage() {
  const { t } = useLanguage();
  return <main id="main" className="policy-page page-container"><div className="policy-icon"><ShieldCheck size={21} /></div><p className="eyebrow"><span className="eyebrow-dot" />LOCAL-FIRST LEARNING</p><h1>{t('privacyTitle')}</h1><p className="policy-lede">This self-paced course does not require an account and does not send study activity to a server.</p><div className="policy-content"><h2>What is stored</h2><p>Language preference, lesson completion, quiz scores, saved words, study dates and word-review results are stored in your browser’s local storage on this device. The course does not submit them to Vietsound.</p><h2>Enquiry forms</h2><p>This learning version has no registration or payment form. No personal details are collected by the course pages.</p><h2>Audio and microphone</h2><p>Listen buttons use the browser or operating system’s speech synthesis service; depending on the selected voice and device settings, processing may be local or handled by that provider. This site does not capture your playback. The optional “Record yourself” tool requests microphone permission only when you choose to start recording. Audio stays in the page’s temporary memory, is never uploaded or saved to an account, and is discarded when you clear it or leave the page unless you explicitly download it.</p><h2>Deleting your data</h2><p>Use “Reset my progress” on the progress page to clear course data stored by the app, or clear this site’s storage in your browser settings.</p><div className="policy-source-note"><Sparkles size={17} /><p>The original Canva site included a Canva-specific data notice. It is not included here because this React version does not use Canva to process learning data.</p></div></div><Link className="back-link" to="/course"><ArrowLeft size={16} />Back to course</Link></main>;
}

export function TermsPage() {
  const { t } = useLanguage();
  return <main id="main" className="policy-page page-container"><div className="policy-icon"><BookOpen size={21} /></div><p className="eyebrow"><span className="eyebrow-dot" />LEARNING GUIDANCE</p><h1>{t('termsTitle')}</h1><p className="policy-lede">A clear description of what this self-paced course does—and does not do.</p><div className="policy-content"><h2>Educational material</h2><p>Lessons and examples are provided for language-learning practice. Vietnamese usage varies by region, age, relationship and situation. Use the examples as a starting point and seek local guidance for sensitive contexts.</p><h2>Progress and accounts</h2><p>Course pages are open to use. Progress and saved words remain in the current browser on the current device. There is no user account, payment or cross-device synchronisation in this version.</p><h2>Audio and recordings</h2><p>Speech synthesis is provided by the browser or operating system and may be processed locally or by that provider; it may not match a native speaker’s accent or pronunciation. Written examples remain available if audio is not supported. Optional microphone practice runs only after you give permission; recordings stay temporarily in the page, are never sent to a server and disappear when cleared or when you leave unless you download them.</p><h2>Course content scope</h2><p>The A1 beginner path contains twelve original structured lessons. The story library is a supplementary starter collection, not the full 200+ story archive mentioned on the source landing page.</p><div className="policy-source-note"><ShieldCheck size={17} /><p>For an official commercial release, the Vietsound owner should confirm content rights, attribution, translations, accessibility and any business terms.</p></div></div><Link className="back-link" to="/course"><ArrowLeft size={16} />Back to course</Link></main>;
}

export function NotFoundPage() {
  const { t } = useLanguage();
  return <main id="main" className="not-found-page page-container"><span className="not-found-glyph" aria-hidden="true">ơ</span><p className="eyebrow"><span className="eyebrow-dot" />404 · NOT FOUND</p><h1>We can’t find that page.</h1><p>Return to your course and keep going.</p><ButtonLink to="/" kind="coral">{t('back') || 'Back home'}</ButtonLink></main>;
}
