import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const copy = {
  en: {
    skip: 'Skip to content', navCourse: 'Course', navPronunciation: 'Pronunciation', navDictionary: 'Dictionary', navStories: 'Stories', navProgress: 'My progress', navJournal: 'Study notes', navReview: 'Word review', navHelp: 'Help', navAbout: 'About', openCourse: 'Open course', closeMenu: 'Close navigation', menu: 'Open navigation',
    homeEyebrow: 'YOUR VIETNAMESE LEARNING SPACE', homeTitle: 'Learn Vietnamese,', homeAccent: 'one useful lesson at a time.', homeBody: 'A self-paced A1 path: hear the sounds, understand the patterns, practise with stories and check what you know.',
    continueLearning: 'Continue learning', startLearning: 'Start lesson 1', courseMap: 'Course map', yourProgress: 'Your progress', lessonsComplete: 'lessons complete', wordsLearned: 'words in the course', minutesPerLesson: 'minutes per lesson', dailyPractice: 'A little every day', nextStep: 'NEXT IN YOUR COURSE', resumeLesson: 'Resume your last lesson', courseComplete: 'Course complete', reviewLastLesson: 'Review last lesson', courseStart: 'Start the course', currentLesson: 'CURRENT LESSON', completedLabel: 'Completed', notStarted: 'Not started', courseOverview: 'A1 · BEGINNER COURSE', courseTitle: 'Vietnamese for everyday life', courseSummary: 'Twelve guided lessons that take you from greetings to a complete first conversation. No account or payment needed; your progress stays on this device.',
    unit: 'UNIT', lesson: 'LESSON', lessonObjectives: 'What you will learn', vocabulary: 'Key words', grammar: 'Language pattern', dialogue: 'Listen and read', practice: 'Check your understanding', completeLesson: 'Finish lesson', retryLesson: 'Try again', showAnswer: 'Check answer', nextLesson: 'Next lesson', previousLesson: 'Previous lesson', courseHome: 'Course outline', lessonComplete: 'Lesson complete', lessonPassed: 'You passed this lesson. Your progress has been saved on this device.', lessonTryAgain: 'Review the lesson and try the questions again.', question: 'Question', score: 'Score', correct: 'Correct', incorrect: 'Not quite', playLine: 'Listen to this line', typeAnswer: 'Type your answer', chooseAnswer: 'Choose one answer', yourAnswer: 'Your answer', lessonNote: 'The English explanation is a learning aid; Vietnamese usage changes by region and relationship.',
    pronunciationIntro: 'Hear the sounds before you chase the accent.', dictionaryIntro: 'Search words, examples and explanations from the course.', searchWords: 'Search Vietnamese or English…', allCategories: 'All words', savedWords: 'Saved words', saveWord: 'Save word', removeSavedWord: 'Remove saved word', noWords: 'No words match this search.', wordCount: 'course words', reviewIntro: 'Practise the words you saved. Flip each card, recall the meaning, then mark it known.', flipCard: 'Show meaning', gotIt: 'I knew it', stillLearning: 'Practise again', emptyReview: 'No saved words yet. Save words from the dictionary to build your review deck.',
    storiesIntro: 'Short comprehensible stories. Read, listen, notice new words and answer a question.', allStories: 'All stories', storyQuestion: 'Check the story', storyDone: 'Story practised', noStories: 'No story matches this filter.',
    progressIntro: 'Your study history is saved in this browser, without an account.', resetProgress: 'Reset my progress', resetConfirm: 'Reset all course progress and saved words on this device?', studyDays: 'Study days', attempts: 'Attempts', bestScore: 'Best score', noAttempts: 'No attempts yet', printCertificate: 'Print course record', certificate: 'Vietsound course record', certificateBody: 'has completed the A1 beginner course Vietnamese for everyday life.',
    journalIntro: 'Useful notes on words, grammar and the way Vietnamese is used.', readNote: 'Read note', aboutTitle: 'A course built around real communication', aboutBody: 'Vietsound combines sound practice, comprehensible stories and focused grammar so learners can understand first and speak with more confidence.', helpTitle: 'Help with studying', helpBody: 'This course runs in your browser. Your answers and progress are stored locally on this device.', helpQ1: 'Do I need an account?', helpA1: 'No. Lessons are open. Progress and saved words stay in local browser storage on this device.', helpQ2: 'Can I use the audio?', helpA2: 'The listen buttons use the Vietnamese voice installed in your browser or operating system. If no Vietnamese voice is available, your device may use a default voice.', helpQ3: 'How do I finish a lesson?', helpA3: 'Read and listen to the lesson, complete the questions, then score at least 67%. You can retry any lesson at any time.', helpQ4: 'Does this course replace a teacher?', helpA4: 'It is a self-paced course. A teacher can help with feedback, regional pronunciation and social context, but no booking is required to use the course.', helpQ5: 'Are my voice recordings uploaded?', helpA5: 'No. The optional recorder runs only after you start it and grant microphone permission. The recording stays in this page, unless you choose to download it; it is never uploaded.',
    footerContinue: 'Pick up where you left off.', footerContinueBody: 'Your course, saved words and progress are right here on this device.', footerTagline: 'A practical Vietnamese course for curious learners.', footerLearn: 'LEARN', footerPractice: 'PRACTISE', footerSupport: 'INFORMATION', privacy: 'Privacy', terms: 'Terms', privacyTitle: 'Privacy', termsTitle: 'Terms of use',
    clearSearch: 'Clear', level: 'Level', duration: 'Duration', noResult: 'Nothing found', back: 'Back', today: 'today', saved: 'Saved', language: 'Language',
  },
  vi: {
    skip: 'Chuyển đến nội dung', navCourse: 'Khóa học', navPronunciation: 'Phát âm', navDictionary: 'Từ điển', navStories: 'Câu chuyện', navProgress: 'Tiến độ', navJournal: 'Ghi chú', navReview: 'Ôn từ', navHelp: 'Trợ giúp', navAbout: 'Giới thiệu', openCourse: 'Vào khóa học', closeMenu: 'Đóng điều hướng', menu: 'Mở điều hướng',
    homeEyebrow: 'KHÔNG GIAN HỌC TIẾNG VIỆT CỦA BẠN', homeTitle: 'Học tiếng Việt,', homeAccent: 'mỗi lần một bài học.', homeBody: 'Khóa học sơ cấp tự học gồm mười hai bài: nghe âm thanh, hiểu cấu trúc, luyện qua câu chuyện và kiểm tra kiến thức.',
    continueLearning: 'Tiếp tục học', startLearning: 'Bắt đầu bài 1', courseMap: 'Lộ trình khóa học', yourProgress: 'Tiến độ của bạn', lessonsComplete: 'bài đã hoàn thành', wordsLearned: 'từ trong khóa học', minutesPerLesson: 'phút mỗi bài', dailyPractice: 'Học một chút mỗi ngày', nextStep: 'BƯỚC TIẾP THEO', resumeLesson: 'Tiếp tục bài học gần nhất', courseComplete: 'Đã hoàn thành khóa học', reviewLastLesson: 'Ôn lại bài cuối', courseStart: 'Bắt đầu khóa học', currentLesson: 'BÀI HỌC HIỆN TẠI', completedLabel: 'Đã hoàn thành', notStarted: 'Chưa bắt đầu', courseOverview: 'A1 · SƠ CẤP', courseTitle: 'Tiếng Việt trong đời sống', courseSummary: 'Mười hai bài học có hướng dẫn, từ chào hỏi đến cuộc trò chuyện đầu tiên. Không cần tài khoản hay thanh toán; tiến độ được lưu trên thiết bị này.',
    unit: 'CHỦ ĐỀ', lesson: 'BÀI', lessonObjectives: 'Bạn sẽ học được', vocabulary: 'Từ khóa', grammar: 'Cấu trúc ngôn ngữ', dialogue: 'Nghe và đọc', practice: 'Kiểm tra kiến thức', completeLesson: 'Hoàn thành bài', retryLesson: 'Làm lại', showAnswer: 'Kiểm tra', nextLesson: 'Bài tiếp theo', previousLesson: 'Bài trước', courseHome: 'Lộ trình khóa học', lessonComplete: 'Đã hoàn thành bài học', lessonPassed: 'Bạn đã vượt qua bài học. Tiến độ được lưu trên thiết bị này.', lessonTryAgain: 'Ôn lại bài học và thử câu hỏi lần nữa.', question: 'Câu hỏi', score: 'Điểm', correct: 'Chính xác', incorrect: 'Chưa đúng', playLine: 'Nghe câu này', typeAnswer: 'Nhập câu trả lời', chooseAnswer: 'Chọn một đáp án', yourAnswer: 'Câu trả lời', lessonNote: 'Phần giải thích tiếng Anh chỉ hỗ trợ học tập; cách dùng tiếng Việt thay đổi theo vùng miền và mối quan hệ.',
    pronunciationIntro: 'Lắng nghe âm thanh trước khi bắt chước giọng.', dictionaryIntro: 'Tìm từ, ví dụ và giải thích trong khóa học.', searchWords: 'Tìm từ tiếng Việt hoặc tiếng Anh…', allCategories: 'Tất cả từ', savedWords: 'Từ đã lưu', saveWord: 'Lưu từ', removeSavedWord: 'Bỏ lưu từ', noWords: 'Không tìm thấy từ phù hợp.', wordCount: 'từ trong khóa học', reviewIntro: 'Ôn những từ bạn đã lưu. Lật thẻ, nhớ nghĩa rồi đánh dấu đã biết.', flipCard: 'Xem nghĩa', gotIt: 'Đã nhớ', stillLearning: 'Cần ôn thêm', emptyReview: 'Chưa có từ đã lưu. Hãy lưu từ trong từ điển để tạo bộ ôn tập.',
    storiesIntro: 'Đọc truyện ngắn, nghe, chú ý từ mới và trả lời câu hỏi.', allStories: 'Tất cả câu chuyện', storyQuestion: 'Kiểm tra nội dung', storyDone: 'Đã luyện truyện', noStories: 'Không tìm thấy câu chuyện phù hợp.',
    progressIntro: 'Lịch học được lưu trong trình duyệt này, không cần tài khoản.', resetProgress: 'Xóa tiến độ', resetConfirm: 'Xóa toàn bộ tiến độ khóa học và từ đã lưu trên thiết bị này?', studyDays: 'Ngày học', attempts: 'Lần làm', bestScore: 'Điểm cao nhất', noAttempts: 'Chưa làm bài', printCertificate: 'In bảng ghi nhận', certificate: 'Bảng ghi nhận khóa học Vietsound', certificateBody: 'đã hoàn thành khóa học sơ cấp Tiếng Việt trong đời sống.',
    journalIntro: 'Ghi chú hữu ích về từ vựng, ngữ pháp và cách dùng tiếng Việt.', readNote: 'Đọc ghi chú', aboutTitle: 'Khóa học hướng đến giao tiếp thực tế', aboutBody: 'Vietsound kết hợp luyện âm, câu chuyện dễ hiểu và ngữ pháp có trọng tâm để người học hiểu trước rồi tự tin giao tiếp hơn.', helpTitle: 'Trợ giúp học tập', helpBody: 'Khóa học chạy trong trình duyệt. Câu trả lời và tiến độ được lưu trên thiết bị này.', helpQ1: 'Tôi có cần tài khoản không?', helpA1: 'Không. Bài học được mở. Tiến độ và từ đã lưu nằm trong bộ nhớ trình duyệt trên thiết bị này.', helpQ2: 'Tôi có thể nghe âm thanh không?', helpA2: 'Nút nghe sử dụng giọng tiếng Việt có sẵn trong trình duyệt hoặc hệ điều hành. Nếu không có, thiết bị có thể dùng giọng mặc định.', helpQ3: 'Làm thế nào để hoàn thành bài học?', helpA3: 'Đọc và nghe bài học, làm câu hỏi, sau đó đạt ít nhất 67%. Bạn có thể làm lại bất kỳ bài nào.', helpQ4: 'Khóa học có thay thế gia sư không?', helpA4: 'Đây là khóa học tự học. Gia sư có thể góp ý về phát âm vùng miền và ngữ cảnh xã hội, nhưng bạn không cần đặt lịch để học.', helpQ5: 'Bản ghi giọng nói có được tải lên không?', helpA5: 'Không. Công cụ ghi âm chỉ hoạt động khi bạn bấm bắt đầu và cấp quyền truy cập micrô. Bản ghi ở trong trang này trừ khi bạn tự tải xuống; âm thanh không bao giờ được gửi lên máy chủ.',
    footerContinue: 'Tiếp tục từ nơi bạn dừng lại.', footerContinueBody: 'Khóa học, từ đã lưu và tiến độ đều ở trên thiết bị này.', footerTagline: 'Khóa học tiếng Việt thực tế dành cho người ham học.', footerLearn: 'HỌC', footerPractice: 'LUYỆN TẬP', footerSupport: 'THÔNG TIN', privacy: 'Quyền riêng tư', terms: 'Điều khoản', privacyTitle: 'Quyền riêng tư', termsTitle: 'Điều khoản sử dụng',
    clearSearch: 'Xóa', level: 'Trình độ', duration: 'Thời lượng', noResult: 'Không tìm thấy', back: 'Quay lại', today: 'hôm nay', saved: 'Đã lưu', language: 'Ngôn ngữ',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem('vietsound-language') === 'vi' ? 'vi' : 'en'; } catch { return 'en'; }
  });
  useEffect(() => {
    document.documentElement.lang = lang;
    try { localStorage.setItem('vietsound-language', lang); } catch { /* ignore blocked storage */ }
  }, [lang]);
  const value = useMemo(() => ({ lang, setLang, t: (key) => copy[lang][key] ?? copy.en[key] ?? key }), [lang]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
